### ISSUE TITLE
Proposal: Charts/Visualization of data (draft in comment)

### ISSUE THREAD

**Issue by GavinRay97** [jerpdoesgames/EldenRingSpellComparer#8]
I added Chart.js and hooked it up to the dynamically calculated data:

The code changes are pretty big, to make the function that calculates the spell data able to be called statically outside of the class instance. So I will attach as a zip if you're curious instead of filing a PR for this WIP

https://user-images.githubusercontent.com/26604994/169879531-fe301ee9-1b9b-4e82-a2be-9c99aa96182c.mp4

[EldenRingSpellConverter-Charts.zip](https://github.com/jerpdoesgames/EldenRingSpellComparer/files/8757108/EldenRingSpellConverter-Charts.zip)

**Comment by jerpdoesgames** [comment]
Barely had a chance to glance at this but wanted at least leave a couple of notes:

- I'm apprehensive re: adding any libraries at this point as (despite my code needing a lot of cleanup) I've wanted the tool to be relatively slim and quick to load (especially without any external dependencies).
- How's mobile support in Chart.js? (both in terms of general functionality and also just ensuring that everything fits and remains readable on screen - the current live version of the tool is generally usable on both desktop and mobile)
- How easily can Chart.js be customized/skinned?
- I'm not sure if the initial view in the attached video shows data that I think people would find actionable for their builds.  I can elaborate on this later/over the weekend.

**Comment by GavinRay97** [comment]
> I'm apprehensive re: adding any libraries at this point as (despite my code needing a lot of cleanup) I've wanted the tool to be relatively slim and quick to load (especially without any external dependencies).

One way to do this would be not to load Chart.js at all unless a user clicks a button like `VISUALIZE` which opens an overlay modal with charts/other visualizations.

You can dynamically add scripts to page source after load. So on clicking the button, the Chart.js source could be fetched.

> How's mobile support in Chart.js? (both in terms of general functionality and also just ensuring that everything fits and remains readable on screen - the current live version of the tool is generally usable on both desktop and mobile)

Yeah, fair point -- it's one of the most popular charting libraries for the web so they have solid facilities for responsiveness and being mobile-friendly:

- https://www.chartjs.org/docs/latest/configuration/responsive.html
- https://www.chartjs.org/docs/latest/configuration/device-pixel-ratio.html

> How easily can Chart.js be customized/skinned?

Pretty easily, see here for a highly customized chart I've done previously (the very top chart is a heavily skinned Chart.js line chart)
- https://github.com/hasura/graphql-bench#introduction

![](https://raw.githubusercontent.com/hasura/graphql-bench/master/app/hasura-bench-report.gif)

**Comment by jerpdoesgames** [comment]
I think I'm probably wanting to decline this proposal unless I can come up with some compelling ways to display the data in charts (especially w/regards to common questions players might ask) - so far I think the table is _generally_ fine outside of wanting to color scale some of the values to highlight noteworthy highs and lows (similar to the [Dark Souls 3 example](https://docs.google.com/spreadsheets/d/1tdQXddiMfDfPYdMfqgm_KJDJRZX-eOVMiXske8-n450/pubhtml?gid=1874114326&single=true) I posted earlier).

Especially as, outside of the fonts (which I think I'm going to remove - I'm not even enjoying the aesthetic at this point - especially since I think it's hampering readability), Chart.js is larger than the rest of the project combined.

![chart_js_network](https://user-images.githubusercontent.com/80368438/170806820-6f06bffa-84c2-453e-8a32-d19c16e07996.png)

Definitely a tool to keep in mind, though.

**Comment by GavinRay97** [comment]
Fair enough, will close this one
